[package]
name = "week_3"
version = "0.1.0"
edition = "2024"

[lib]
name = "week_3"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
sha2 = "0.10"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"